name: NarutoUHC
version: 0.0.1
main: com.narutouhc.plugin.Main
author: [Illyes, DrasticLp]
commands:
  role:
    description: Permet de déterminer son rôle
    permission: narutouhc.role
  start:
    description: Permet lancer la partie
    permission: narutouhc.start
  me:
    description: Permet de connaitre des informations sur son rôle
    permission: narutouhc.me
  fs:
    description: Force le lancement de la partie
    permission: narutouhc.fs
  ep:
    description: Change l'épisode
    permission: narutouhc.ep
  inv:
    description: Permet de changer l'inventaire de départ
    permission: narutouhc.inv
  info:
    description: Permet d'envoyer un message anonyme
    permission: narutouhc.info