name: NarutoUHC
version: 0.0.1
main: com.narutouhc.plugin.Main
author: [Illyes, DrasticLp]
commands:
  role:
    description: Permet de déterminer son rôle
    permission: narutouhc.role
  start:
    description: Permet lancer la partie
    permission: narutouhc.start
  me:
    description: Permet de connaitre des informations sur son rôle
    permission: narutouhc.me
  fs:
    description: Force le lancement de la partie
    permission: narutouhc.fs
  ep:
    description: Change l'épisode
    permission: narutouhc.ep
  inv:
    description: Permet de changer l'inventaire de départ
    permission: narutouhc.inv
  info:
    description: Permet d'envoyer un message anonyme
    permission: narutouhc.info
  config:
    description: Permet de configurer le plugin
    permission: narutouhc.config
  spec:
    description: Permet de se mettre spectateur de la partie
    permission: narutouhc.spec
  allow:
    description: Permet d'ajouter un joueur dans la whitelist
    permission: narutouhc.allow
  blacklist:
    description: Permet d'enlever un joueur de la whitelist
    permission: narutouhc.blacklist
  getrole:
    description: Permet de connaître le rôle d'un joueur
    permission: narutouhc.getrole